# Generated by Django 2.2.16 on 2020-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'echoes',
            },
        ),
    ]
