# Generated by Django 2.2.17 on 2020-11-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(help_text='Use reStructuredText here.')),
            ],
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(help_text='Uses markdown here.')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echoes.Utterance')),
            ],
            options={
                'verbose_name_plural': 'echoes',
            },
        ),
    ]
